version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_wp
      MYSQL_PASSWORD: UnMotDePasseTresSolide
      MYSQL_ROOT_PASSWORD: UnAutreMotDePasseTresSolide
    volumes:
      - /mnt/mysql:/var/lib/mysql
    networks:
      - wordpress-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_PASSWORD: UnMotDePasseTresSolide
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /mnt/wordpress:/var/www/html
    networks:
      - wordpress-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == worker

networks:
  wordpress-net:
    driver: overlay


